import Head from 'next/head'
import Image from 'next/image'
import Body from '../components/Common/Body'
import LoadingScreen from '../components/Common/LoadingScreen'
import Question from '../components/Quiz/Question'
import Link from 'next/link'
import NavBar from '../components/Common/NavBar'

export default function Home() {
  return (
    <>
    <LoadingScreen />
      <div>
        <Head>
          <title>Starwars - Which character are you?</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


        <NavBar></NavBar>
        <Body>
          <h1>
            Are you ready to take the quiz?
          </h1>
          <Link href="/quiz" className='bg-yellow-500 text-white active:bg-yellow-600 font-bold uppercase text-sm px-6 py-2 rounded-md hover:bg-yellow-300 ease-linear transition-all duration-150'>Take me there!</Link>
        </Body>

      </div>
    </>
  )
}
